version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "UTC"
      time: "04:00"
    open-pull-requests-limit: 1
    allow:
      - dependency-type: "direct"
    ignore: []
    versioning-strategy: "increase"
    labels:
      - dependencies
    groups:
      pip-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "UTC"
      time: "04:00"
    open-pull-requests-limit: 1
    target-branch: "main"
    labels:
      - dependencies
    groups:
        pip-dependencies:
          patterns:
            - "*"
