name: Pre-Release

on:
  push:
    branches: ["*"]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (optional)'
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          # Ensure the latest ruff is used regardless of constraints
          pip install --upgrade ruff

      - name: Run ruff formatting check (no changes)
        run: |
          ruff --version
          ruff format --check
