name: Pre-Release

on:
  push:
    branches: ["*"]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (optional)'
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run ruff lint
        run: ruff format

  notify-release:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - uses: actions/checkout@v4
      - name: Trigger Release Workflow
        run: |
          if [ -n "$VERSION_INPUT" ]; then
          gh workflow run .github/workflows/release.yml -f version="$VERSION_INPUT"
          else
          gh workflow run release.yml
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_INPUT: ${{ inputs.version }}