name: Pre-Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make unittest

  notify-release:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Release
          token: ${{ secrets.GITHUB_TOKEN }}
