name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (optional)'
        required: false
  workflow_run:
    workflows: ['Pre-Release']
    types: [completed]

permissions:
  contents: write

jobs:
  release:
    # Run if manually dispatched OR if Pre-Release succeeded on main
    if: >-
      ${{ github.event_name == 'workflow_dispatch' ||
          (github.event_name == 'workflow_run' &&
           github.event.workflow_run.conclusion == 'success' &&
           github.event.workflow_run.head_branch == 'main') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          # For workflow_run, ensure we checkout the branch that triggered Pre-Release
          ref: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_branch || github.ref }}

      - name: Determine target branch
        run: |
          if [ "${{ github.event_name }}" = "workflow_run" ]; then
            echo "TARGET_BRANCH=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV
          else
            echo "TARGET_BRANCH=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          fi

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install bump-my-version
        run: pip install bump-my-version

      - name: Set or bump version
        id: bump
        run: |
          if [ -n "${{ inputs.version }}" ]; then
            bump-my-version set "${{ inputs.version }}"
          else
            bump-my-version bump patch
          fi
          echo "new_version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Verify changelog
        run: |
          NEW_VERSION="${{ steps.bump.outputs.new_version }}"
          if ! grep -q "^# ${NEW_VERSION}" CHANGELOG.md; then
            echo "CHANGELOG.md missing entry for version ${NEW_VERSION}"
            exit 1
          fi
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -n "$PREV_TAG" ]; then
            if ! git diff --name-only "$PREV_TAG" HEAD^ | grep -q '^CHANGELOG.md$'; then
              echo "CHANGELOG.md was not modified since $PREV_TAG"
              exit 1
            fi
          fi

      - name: Push changes and tags
        run: |
          # Push commit to the same branch and include tags
          git push origin HEAD:$TARGET_BRANCH --follow-tags

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.bump.outputs.new_version }}
          name: Release v${{ steps.bump.outputs.new_version }}
          body: |
            ## Changes in v${{ steps.bump.outputs.new_version }}

            Automated release created by GitHub Actions.

            See CHANGELOG.md for detailed changes.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
