name: Run against MockCA

on:
  workflow_run:
    workflows: ["Check code quality"]
    types:
      - completed
  workflow_dispatch:

jobs:
  prepare_env:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    outputs:
      image_lc: ${{ steps.setenv.outputs.image_lc }}
    steps:
      - name: Set lowercase image name
        id: setenv
        run: |
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_LC="ghcr.io/${OWNER_LC}/cmp-mock-ca:latest"
          echo "image_lc=$IMAGE_LC" >> $GITHUB_OUTPUT

  run_tests:
    needs: prepare_env
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    env:
      IMAGE: ${{ needs.prepare_env.outputs.image_lc }}
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: docker run --rm -v "$PWD:/workspace" -w /workspace "$IMAGE" robot --pythonpath=./ --exclude verbose-tests --outputdir=reports --variable environment:mock_ca tests
      - name: Run verbose tests
        run: docker run --rm -v "$PWD:/workspace" -w /workspace "$IMAGE" robot --pythonpath=./ --outputdir=reports --variable environment:mock_ca tests
      - name: Run PQ/Hybrid tests
        run: docker run --rm -v "$PWD:/workspace" -w /workspace "$IMAGE" robot --pythonpath=./ --exclude verbose-tests --outputdir=reports --variable environment:mock_ca tests_pq_and_hybrid
      - name: Run mock CA tests
        run: docker run --rm -v "$PWD:/workspace" -w /workspace "$IMAGE" robot --pythonpath=./ --exclude verbose-tests --outputdir=reports --variable environment:mock_ca tests_mock_ca