name: After Merge Workflow
on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build_mock_ca_image_and_push:
    name: Build & push Mock-CA image
    runs-on: ubuntu-22.04
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Mock-CA image
        env:
          OWNER_LC: ${{ github.repository_owner }}
        run: |
          OWNER_LC=$(echo "$OWNER_LC" | tr '[:upper:]' '[:lower:]')
          docker buildx build \
            -t ghcr.io/${OWNER_LC}/mock-ca:${{ github.sha }} \
            -t ghcr.io/${OWNER_LC}/mock-ca:latest \
            --push \
            -f data/dockerfiles/Dockerfile.mock_ca .
